-- Insert into all_aliases or update if the name already exists
INSERT INTO all_aliases (name)
VALUES
('Abyssal demons'),
('Corrupted kalphites'),
('Corrupted worker'),
('Ripper Demon'),
('Acheron mammoth'),
('Gorak'),
('Kal''gerion demon'),
('Kurasks'),
('Aviansie'),
('Glacor'),
('Greater demon ash lords'),
('Gorilla akh'),
('Kalphites'),
('Risen ghost'),
('Corrupted scarabs'),
('Flesh Crawlers'),
('Lost Grove creatures'),
('Volcanic creatures'),
('Nightmare'),
('Cockatrices'),
('Suqah'),
('Fungal mages'),
('Camel Warrior'),
('Ankous'),
('Feline akh'),
('Rune dragon'),
('Rock slugs'),
('Imperial guard akh'),
('Corrupted scorpions'),
('Greater demon berserkers'),
('Automatons'),
('Corrupted dust devils'),
('Crocodile akh'),
('Scarab akh'),
('Salawa akh'),
('Soul devourer'),
('Cave slime'),
('Tormented demon'),
('Corrupted lizards')
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    updated_at = NOW();
