-- Insert into all_assignments or update if the index already exists
INSERT INTO all_assignments (`index`, default_creature)
VALUES
('Aberrant spectres', 'Aberrant spectre#Slayer Tower'),
('Abyssal Demons', 'Abyssal demon#Default'),
('Abyssal beasts', 'Abyssal beast#Default'),
('Abyssal lords', 'Abyssal lord#Default'),
('Abyssal savages', 'Abyssal savage#Asylum'),
('Acheron mammoths', 'Acheron mammoth#Default'),
('Adamant dragons', 'Adamant dragon#Default'),
('Airut', 'Airut#Melee'),
('Ankou', 'Ankou#Default'),
('Aquanites', 'Aquanite#Default'),
('Armoured phantoms', 'Armoured phantom#1'),
('Ascension members', 'Capsarius#1'),
('Aviansies', 'Kree''arra#Normal'),
('Banshees', 'Banshee#Default'),
('Basilisks', 'Basilisk#Large'),
('Bats', 'Bat#Default'),
('Bears', 'Black bear#Default'),
('Birds', 'Chicken#White'),
('Black demons', 'Black demon#1'),
('Black dragons', 'Queen Black Dragon#Normal'),
('Bloodveld', 'Bloodveld#Default'),
('Blue dragons', 'Blue dragon#1'),
('Bound skeletons', 'Bound skeleton#1'),
('Brine rats', 'Brine rat#Default'),
('Bronze dragons', 'Bronze dragon#Default'),
('Camel warriors', 'Camel Warrior#Default'),
('Catablepon', 'Catablepon#Default'),
('Cave bugs', 'Cave bug#Level 11'),
('Cave crawlers', 'Cave crawler#Level 24'),
('Cave horrors', 'Unspeakable horror#Default'),
('Cave slimes', 'Cave slime#Default'),
('Celestial dragons', 'Celestial dragon#Default'),
('Chaos giants', 'Chaos Giant#Default'),
('Cockatrice', 'Cockatrice#Default'),
('Cockroaches', 'Cockroach drone#Default'),
('Corrupted creatures', 'Corrupted scorpion#Default'),
('Cows', 'Cow#Standard (1)'),
('Crawling hands', 'Crawling hand#10a'),
('Creatures of Daemonheim', 'Edimmu#Default'),
('Creatures of the Lost Grove', 'Bulbous crawler#Default'),
('Cres''s creations', 'Automaton Generator#Post-quest'),
('Crocodiles', 'Crocodile#40'),
('Crystal shapeshifters', 'Crystal Shapeshifter#Magic'),
('Cyclopes', 'Cyclops#57 (Crush)'),
('Dagannoth', 'Dagannoth Rex#Default'),
('Dark beasts', 'Dark beast#19,000 life points'),
('Demons', 'K''ril Tsutsaroth#Normal'),
('Desert lizards', 'Corrupted lizard#Default'),
('Desert strykewyrms', 'Desert strykewyrm#Default'),
('Dinosaurs', 'Ripper dinosaur#Normal'),
('Dogs', 'Jackal#Default'),
('Dragons', 'Queen Black Dragon#Normal'),
('Dust devils', 'Corrupted dust devil#Default'),
('Earth warriors', 'Earth warrior#Default'),
('Edimmu', 'Edimmu#Default'),
('Elves', 'Elf warrior#Melee'),
('Fetid zombies', 'Fetid zombie#1'),
('Fever spiders', 'Fever spider#Default'),
('Fire giants', 'Fire giant#Default'),
('Fleshcrawlers', 'Flesh Crawler#Default'),
('Frogs', 'Plague frog#Default'),
('Fungal magi', 'Fungal mage#Normal'),
('Ganodermic creatures', 'Ganodermic beast#Normal'),
('Gargoyles', 'Gargoyle#Regular'),
('Gelatinous abominations', 'Gelatinous abomination#Default'),
('Gemstone dragons', 'Hydrix dragon#Default'),
('Ghosts', 'Ghost#1'),
('Ghouls', 'Ravenous ghoul#Default'),
('Glacors', 'Arch-Glacor#Normal mode'),
('Goblins', 'Goblin#Level 11'),
('Goraks', 'Gorak#God Wars Dungeon'),
('Greater demon berserkers and ash lords', 'Greater demon ash lord#Wilderness'),
('Greater demons', 'K''ril Tsutsaroth#Normal'),
('Green dragons', 'Green dragon#1'),
('Grifolapines', 'Grifolapine#Normal'),
('Grifolaroos', 'Grifolaroo#Normal'),
('Grotworms', 'Mature grotworm#Default'),
('Harpie bug swarms', 'Harpie Bug Swarm#Default'),
('Hellhounds', 'Hellhound#Normal'),
('Hill giants', 'Hill Giant#Default'),
('Hobgoblins', 'Hobgoblin#Level 15'),
('Hydrix dragons', 'Hydrix dragon#Default'),
('Ice giants', 'Ice giant#Level 47 (1)'),
('Ice strykewyrms', 'Ice strykewyrm#Default'),
('Ice warriors', 'Ice warrior#Normal'),
('Icefiends', 'Icefiend#God Wars Dungeon'),
('Infernal mages', 'Infernal Mage#Default'),
('Iron dragons', 'Iron dragon#Default'),
('Jellies', 'Jelly#Default'),
('Jungle horrors', 'Jungle horror#Default'),
('Jungle strykewyrms', 'Jungle strykewyrm#Default'),
('Kal''gerion demons', 'Kal''gerion demon#Bloodchiller'),
('Kalphite', 'Corrupted kalphite guardian#Default'),
('Killerwatts', 'Killerwatt#Default'),
('Kurask', 'Kurask#Examine #1'),
('Lava strykewyrms', 'Lava strykewyrm#Default'),
('Lesser demons', 'Lesser demon#1'),
('Living rock creatures', 'Living rock patriarch#Default'),
('Living wyverns', 'Wyvern#Default'),
('Minotaurs', 'Minotaur#Level 12'),
('Mithril dragons', 'Mithril dragon#Default'),
('Mogres', 'Mogre#Default'),
('Molanisks', 'Molanisk#Default'),
('Moss giants', 'Moss giant#Common (1)'),
('Muspah', 'Bladed muspah#Default'),
('Mutated jadinkos', 'Mutated jadinko baby#Default'),
('Mutated zygomites', 'Mutated zygomite#Level 58'),
('Nechryael', 'Nechryael#Default'),
('Nightmare creatures', 'Nightmare#Default'),
('Nihil', 'Blood nihil#normal'),
('Nodon dragonkin', 'Nodon guard#Default'),
('Ogres', 'Enclave guard#Default'),
('Onyx dragons', 'Onyx dragon#Default'),
('Otherworldly beings', 'Otherworldly being#Default'),
('Pyrefiends', 'Pyrefiend#Level 38'),
('Rats', 'Warped rat#Default'),
('Red dragons', 'Red dragon#1'),
('Revenants', 'Revenant cyclops#Default'),
('Ripper demons', 'Ripper Demon#Default'),
('Risen ghosts', 'Risen ghost#Default'),
('Rockslugs', 'Rock slug#Default'),
('Rune dragons', 'Rune dragon#Armoured'),
('Scabarites', 'Scarab akh#Default'),
('Scorpions', 'Corrupted scorpion#Default'),
('Sea snakes', 'Sea Snake Hatchling#Default'),
('Shades', 'Shade#Default'),
('Shadow creatures', 'Manifest shadow#Default'),
('Shadow warriors', 'Shadow warrior#Default'),
('Skeletal wyverns', 'Skeletal Wyvern#1'),
('Skeletons', 'Skeleton (Lumbridge Catacombs)#Default'),
('Soul devourers', 'The Magister#Default'),
('Soulgazers', 'Soulgazer#Default'),
('Spiders', 'Deadly red spider#Default'),
('Spiritual mages', 'Spiritual mage#Armadyl'),
('Spiritual warriors', 'Spiritual warrior#Armadyl'),
('Stalker creatures', 'Veil-ripper Ozharakha#Default'),
('Steel dragons', 'Steel dragon#Default'),
('Strykewyrms', 'Desert strykewyrm#Default'),
('Suqahs', 'Suqah#Level 73 (Dual wielding swords)'),
('Terror dogs', 'Terror dog#Level 61'),
('Tormented demons', 'Tormented demon#Standard'),
('Trolls', 'Ice troll runt#Default'),
('Turoth', 'Turoth#60 - Large'),
('TzHaar', 'TzHaar-Hur#Level 86'),
('Undead', 'Ghost#1'),
('Vampyres', 'Vampyre#Default'),
('Vile blooms', 'Liverworts#Default'),
('Vyrewatch', 'Vyrewatch#Level 70'),
('Wall beasts', 'Wall beast#Default'),
('Warped terrorbirds', 'Warped terrorbird#1'),
('Warped tortoises', 'Warped tortoise#Vulnerable'),
('Waterfiends', 'Waterfiend#Default'),
('Werewolves', 'Werewolf#Alexis'),
('Wolves', 'Adolescent White wolf#Default'),
('Zemouregal''s undead', 'Armoured phantom#1'),
('Zombies', 'Zombie#Level 29')
ON DUPLICATE KEY UPDATE
    default_creature = VALUES(default_creature),
    updated_at = NOW();
