-- Insert into all_assignments or update if the index already exists
INSERT INTO all_assignments (`index`, default_creature)
VALUES
('1', 'Aberrant spectres', 'Aberrant spectre#Slayer Tower'),
('2', 'Abyssal Demons', 'Abyssal demon#Default'),
('3', 'Abyssal beasts', 'Abyssal beast#Default'),
('4', 'Abyssal lords', 'Abyssal lord#Default'),
('5', 'Abyssal savages', 'Abyssal savage#Asylum'),
('6', 'Acheron mammoths', 'Acheron mammoth#Default'),
('7', 'Adamant dragons', 'Adamant dragon#Default'),
('8', 'Airut', 'Airut#Melee'),
('9', 'Ankou', 'Ankou#Default'),
('10', 'Aquanites', 'Aquanite#Default'),
('11', 'Armoured phantoms', 'Armoured phantom#1'),
('12', 'Ascension members', 'Capsarius#1'),
('13', 'Aviansies', 'Kree''arra#Normal'),
('14', 'Banshees', 'Banshee#Default'),
('15', 'Basilisks', 'Basilisk#Large'),
('16', 'Bats', 'Bat#Default'),
('17', 'Bears', 'Black bear#Default'),
('18', 'Birds', 'Chicken#White'),
('19', 'Black demons', 'Black demon#1'),
('20', 'Black dragons', 'Queen Black Dragon#Normal'),
('21', 'Bloodveld', 'Bloodveld#Default'),
('22', 'Blue dragons', 'Blue dragon#1'),
('23', 'Bound skeletons', 'Bound skeleton#1'),
('24', 'Brine rats', 'Brine rat#Default'),
('25', 'Bronze dragons', 'Bronze dragon#Default'),
('26', 'Camel warriors', 'Camel Warrior#Default'),
('27', 'Catablepon', 'Catablepon#Default'),
('28', 'Cave bugs', 'Cave bug#Level 11'),
('29', 'Cave crawlers', 'Cave crawler#Level 24'),
('30', 'Cave horrors', 'Unspeakable horror#Default'),
('31', 'Cave slimes', 'Cave slime#Default'),
('32', 'Celestial dragons', 'Celestial dragon#Default'),
('33', 'Chaos giants', 'Chaos Giant#Default'),
('34', 'Cockatrice', 'Cockatrice#Default'),
('35', 'Cockroaches', 'Cockroach drone#Default'),
('36', 'Corrupted creatures', 'Corrupted scorpion#Default'),
('37', 'Cows', 'Cow#Standard (1)'),
('38', 'Crawling hands', 'Crawling hand#10a'),
('39', 'Creatures of Daemonheim', 'Edimmu#Default'),
('40', 'Creatures of the Lost Grove', 'Bulbous crawler#Default'),
('41', 'Cres''s creations', 'Automaton Generator#Post-quest'),
('42', 'Crocodiles', 'Crocodile#40'),
('43', 'Crystal shapeshifters', 'Crystal Shapeshifter#Magic'),
('44', 'Cyclopes', 'Cyclops#57 (Crush)'),
('45', 'Dagannoth', 'Dagannoth Rex#Default'),
('46', 'Dark beasts', 'Dark beast#19,000 life points'),
('47', 'Demons', 'K''ril Tsutsaroth#Normal'),
('48', 'Desert lizards', 'Corrupted lizard#Default'),
('49', 'Desert strykewyrms', 'Desert strykewyrm#Default'),
('50', 'Dinosaurs', 'Ripper dinosaur#Normal'),
('51', 'Dogs', 'Jackal#Default'),
('52', 'Dragons', 'Queen Black Dragon#Normal'),
('53', 'Dust devils', 'Corrupted dust devil#Default'),
('54', 'Earth warriors', 'Earth warrior#Default'),
('55', 'Edimmu', 'Edimmu#Default'),
('56', 'Elves', 'Elf warrior#Melee'),
('57', 'Fetid zombies', 'Fetid zombie#1'),
('58', 'Fever spiders', 'Fever spider#Default'),
('59', 'Fire giants', 'Fire giant#Default'),
('60', 'Fleshcrawlers', 'Flesh Crawler#Default'),
('61', 'Frogs', 'Plague frog#Default'),
('62', 'Fungal magi', 'Fungal mage#Normal'),
('63', 'Ganodermic creatures', 'Ganodermic beast#Normal'),
('64', 'Gargoyles', 'Gargoyle#Regular'),
('65', 'Gelatinous abominations', 'Gelatinous abomination#Default'),
('66', 'Gemstone dragons', 'Hydrix dragon#Default'),
('67', 'Ghosts', 'Ghost#1'),
('68', 'Ghouls', 'Ravenous ghoul#Default'),
('69', 'Glacors', 'Arch-Glacor#Normal mode'),
('70', 'Goblins', 'Goblin#Level 11'),
('71', 'Goraks', 'Gorak#God Wars Dungeon'),
('72', 'Greater demon berserkers and ash lords', 'Greater demon ash lord#Wilderness'),
('73', 'Greater demons', 'K''ril Tsutsaroth#Normal'),
('74', 'Green dragons', 'Green dragon#1'),
('75', 'Grifolapines', 'Grifolapine#Normal'),
('76', 'Grifolaroos', 'Grifolaroo#Normal'),
('77', 'Grotworms', 'Mature grotworm#Default'),
('78', 'Harpie bug swarms', 'Harpie Bug Swarm#Default'),
('79', 'Hellhounds', 'Hellhound#Normal'),
('80', 'Hill giants', 'Hill Giant#Default'),
('81', 'Hobgoblins', 'Hobgoblin#Level 15'),
('82', 'Hydrix dragons', 'Hydrix dragon#Default'),
('83', 'Ice giants', 'Ice giant#Level 47 (1)'),
('84', 'Ice strykewyrms', 'Ice strykewyrm#Default'),
('85', 'Ice warriors', 'Ice warrior#Normal'),
('86', 'Icefiends', 'Icefiend#God Wars Dungeon'),
('87', 'Infernal mages', 'Infernal Mage#Default'),
('88', 'Iron dragons', 'Iron dragon#Default'),
('89', 'Jellies', 'Jelly#Default'),
('90', 'Jungle horrors', 'Jungle horror#Default'),
('91', 'Jungle strykewyrms', 'Jungle strykewyrm#Default'),
('92', 'Kal''gerion demons', 'Kal''gerion demon#Bloodchiller'),
('93', 'Kalphite', 'Corrupted kalphite guardian#Default'),
('94', 'Killerwatts', 'Killerwatt#Default'),
('95', 'Kurask', 'Kurask#Examine #1'),
('96', 'Lava strykewyrms', 'Lava strykewyrm#Default'),
('97', 'Lesser demons', 'Lesser demon#1'),
('98', 'Living rock creatures', 'Living rock patriarch#Default'),
('99', 'Living wyverns', 'Wyvern#Default'),
('100', 'Minotaurs', 'Minotaur#Level 12'),
('101', 'Mithril dragons', 'Mithril dragon#Default'),
('102', 'Mogres', 'Mogre#Default'),
('103', 'Molanisks', 'Molanisk#Default'),
('104', 'Moss giants', 'Moss giant#Common (1)'),
('105', 'Muspah', 'Bladed muspah#Default'),
('106', 'Mutated jadinkos', 'Mutated jadinko baby#Default'),
('107', 'Mutated zygomites', 'Mutated zygomite#Level 58'),
('108', 'Nechryael', 'Nechryael#Default'),
('109', 'Nightmare creatures', 'Nightmare#Default'),
('110', 'Nihil', 'Blood nihil#normal'),
('111', 'Nodon dragonkin', 'Nodon guard#Default'),
('112', 'Ogres', 'Enclave guard#Default'),
('113', 'Onyx dragons', 'Onyx dragon#Default'),
('114', 'Otherworldly beings', 'Otherworldly being#Default'),
('115', 'Pyrefiends', 'Pyrefiend#Level 38'),
('116', 'Rats', 'Warped rat#Default'),
('117', 'Red dragons', 'Red dragon#1'),
('118', 'Revenants', 'Revenant cyclops#Default'),
('119', 'Ripper demons', 'Ripper Demon#Default'),
('120', 'Risen ghosts', 'Risen ghost#Default'),
('121', 'Rockslugs', 'Rock slug#Default'),
('122', 'Rune dragons', 'Rune dragon#Armoured'),
('123', 'Scabarites', 'Scarab akh#Default'),
('124', 'Scorpions', 'Corrupted scorpion#Default'),
('125', 'Sea snakes', 'Sea Snake Hatchling#Default'),
('126', 'Shades', 'Shade#Default'),
('127', 'Shadow creatures', 'Manifest shadow#Default'),
('128', 'Shadow warriors', 'Shadow warrior#Default'),
('129', 'Skeletal wyverns', 'Skeletal Wyvern#1'),
('130', 'Skeletons', 'Skeleton (Lumbridge Catacombs)#Default'),
('131', 'Soul devourers', 'The Magister#Default'),
('132', 'Soulgazers', 'Soulgazer#Default'),
('133', 'Spiders', 'Deadly red spider#Default'),
('134', 'Spiritual mages', 'Spiritual mage#Armadyl'),
('135', 'Spiritual warriors', 'Spiritual warrior#Armadyl'),
('136', 'Stalker creatures', 'Veil-ripper Ozharakha#Default'),
('137', 'Steel dragons', 'Steel dragon#Default'),
('138', 'Strykewyrms', 'Desert strykewyrm#Default'),
('139', 'Suqahs', 'Suqah#Level 73 (Dual wielding swords)'),
('140', 'Terror dogs', 'Terror dog#Level 61'),
('141', 'Tormented demons', 'Tormented demon#Standard'),
('142', 'Trolls', 'Ice troll runt#Default'),
('143', 'Turoth', 'Turoth#60 - Large'),
('144', 'TzHaar', 'TzHaar-Hur#Level 86'),
('145', 'Undead', 'Ghost#1'),
('146', 'Vampyres', 'Vampyre#Default'),
('147', 'Vile blooms', 'Liverworts#Default'),
('148', 'Vyrewatch', 'Vyrewatch#Level 70'),
('149', 'Wall beasts', 'Wall beast#Default'),
('150', 'Warped terrorbirds', 'Warped terrorbird#1'),
('151', 'Warped tortoises', 'Warped tortoise#Vulnerable'),
('152', 'Waterfiends', 'Waterfiend#Default'),
('153', 'Werewolves', 'Werewolf#Alexis'),
('154', 'Wolves', 'Adolescent White wolf#Default'),
('155', 'Zemouregal''s undead', 'Armoured phantom#1'),
('156', 'Zombies', 'Zombie#Level 29')
ON DUPLICATE KEY UPDATE
    index = VALUES(index),
    default_creature = VALUES(default_creature),
    updated_at = NOW();
