-- Insert into all_creatures or update if the name already exists
INSERT INTO all_creatures (name)
VALUES
('Aberrant spectre'),
('Abyssal beast'),
('Abyssal demon'),
('Abyssal demon (elite)'),
('Abyssal lord'),
('Abyssal savage'),
('Acheron mammoth'),
('Adamant dragon'),
('Airut'),
('Ankou'),
('Ankou (Kili''s Knowledge IV)'),
('Ankou (elite)'),
('Aquanite'),
('Aquanite (elite)'),
('Armoured phantom'),
('Capsarius'),
('Gladius'),
('Legio Primus'),
('Legio Quartus'),
('Legio Quintus'),
('Legio Secundus'),
('Legio Sextus'),
('Legio Tertius'),
('Rorarius'),
('Scutarius'),
('Aviansie'),
('Flight Kilisa'),
('Flockleader Geerin'),
('Kree''arra'),
('Spiritual mage'),
('Spiritual ranger'),
('Spiritual warrior'),
('Wingman Skree'),
('Banshee'),
('Mighty banshee'),
('Basilisk'),
('Albino bat'),
('Bat'),
('Giant bat'),
('Warped bat'),
('Angry bear'),
('Bear cub'),
('Black bear'),
('Grizzly bear'),
('Grizzly bear cub'),
('Bird'),
('Chicken'),
('Chompy bird'),
('Duck'),
('Duckling'),
('Jubbly bird'),
('Mounted terrorbird gnome'),
('Oomlie bird'),
('Pekin'),
('Penguin (monster)'),
('Pernicious parrot'),
('Rooster'),
('Seagull'),
('Tenacious toucan'),
('Terrorbird'),
('Undead chicken'),
('Undead pekin'),
('Balfrug Kreeyath'),
('Black demon'),
('Alanogard the Black'),
('Baby black dragon'),
('Black dragon'),
('Black dragon (Dragonkin Laboratory)'),
('King Black Dragon'),
('Queen Black Dragon'),
('Verak Lith'),
('Verak Little'),
('Bloodveld'),
('Bloodveld (God Wars Dungeon)'),
('Bloodveld (Heart of Gielinor)'),
('Mutated bloodveld'),
('Baby blue dragon'),
('Blue dragon'),
('Vorkath'),
('Bound skeleton'),
('Brine rat'),
('Bronze dragon'),
('Camel Warrior'),
('Catablepon'),
('Cave bug'),
('Cave crawler'),
('Cave horror'),
('Cave horror (elite)'),
('Unspeakable horror'),
('Unspeakable horror (elite)'),
('Cave slime'),
('Giant slime'),
('Laboratory slime'),
('Astellarn'),
('Celestial dragon'),
('Celestial dragon (Dragonkin Laboratory)'),
('Elegorn the Celestial'),
('Chaos Giant'),
('Cockatrice'),
('Cockroach drone'),
('Cockroach soldier'),
('Cockroach worker'),
('Warped cockroach'),
('Corrupted dust devil'),
('Corrupted kalphite guardian'),
('Corrupted kalphite marauder'),
('Corrupted lizard'),
('Corrupted scarab'),
('Corrupted scorpion'),
('Corrupted worker'),
('Cow'),
('Cow calf'),
('Super Cow'),
('Undead cow'),
('Crawling hand'),
('Skeletal hand'),
('Zombie hand'),
('Edimmu'),
('Edimmu (elite)'),
('Frost dragon'),
('Kal''gerion demon'),
('Seeker'),
('Soulgazer'),
('Bulbous crawler'),
('Moss golem'),
('Vinecrawler'),
('Automaton Generator'),
('Automaton Guardian'),
('Automaton Tracer'),
('Crocodile'),
('Crocodile akh'),
('Ol'' Sawtooth'),
('Sea crocodile'),
('Crystal Shapeshifter'),
('Cyclops'),
('Cyclossus'),
('Dagannoth (Lighthouse)'),
('Dagannoth (Waterbirth Island)'),
('Dagannoth (Waterbirth Island, ranged)'),
('Dagannoth Prime'),
('Dagannoth Rex'),
('Dagannoth Supreme'),
('Dagannoth fledgeling'),
('Dagannoth guardian'),
('Dagannoth spawn'),
('Dark beast'),
('Dark beast (elite)'),
('Revenant dark beast'),
('Cerberus Juvenile'),
('Gargoyle'),
('Greater demon'),
('Greater demon ash lord'),
('Greater demon berserker'),
('Greater demon brute'),
('Greater demon pyromancer'),
('Greater demon sage'),
('Greater demon savage'),
('Imp'),
('Imp scavenger'),
('K''ril Tsutsaroth'),
('Kal''gerion demon (The Shadow Reef)'),
('Lesser demon'),
('Revenant demon'),
('Ripper Demon'),
('Tormented demon'),
('Tstanon Karlak'),
('Yor''Ger the Deceiver'),
('Zakl''n Gritch'),
('Desert Lizard'),
('Lizard'),
('Small Lizard'),
('Desert strykewyrm'),
('Baby Dinosaur Skeleton'),
('Brutish dinosaur'),
('Feral Dinosaur'),
('Orikalka'),
('Osseous'),
('Pthentraken'),
('Rathis'),
('Ripper dinosaur'),
('Venomous dinosaur'),
('Guard dog'),
('Jackal'),
('Shadow Hound'),
('Wild dog'),
('Baby red dragon'),
('Black stone dragon'),
('Brutal green dragon'),
('Dragonstone dragon'),
('Dragonstone dragon (Dragonkin Laboratory)'),
('Green dragon'),
('Hydrix dragon'),
('Hydrix dragon (Dragonkin Laboratory)'),
('Iron dragon'),
('Mithril dragon'),
('Nodon artificer'),
('Nodon engineer'),
('Nodon guard'),
('Nodon hunter'),
('Onyx dragon'),
('Onyx dragon (Dragonkin Laboratory)'),
('Red dragon'),
('Red dragon (Dragonkin Laboratory)'),
('Rune dragon'),
('Sangri the Red'),
('Siege engine'),
('Steel dragon'),
('Dust devil'),
('Dust devil (elite)'),
('Earth warrior'),
('Earth warrior (elite)'),
('Cadarn magus'),
('Cadarn ranger'),
('Elf warrior'),
('Iorwerth guard'),
('Iorwerth scout'),
('Knight of Ardougne (West Ardougne)'),
('Mourner (Mourner Tunnels)'),
('Seren archer'),
('Seren mage'),
('Seren warrior'),
('Fetid zombie'),
('Fever spider'),
('Fire giant'),
('Flesh Crawler'),
('Big frog'),
('Frog'),
('Frogeel'),
('Giant frog'),
('Plague frog'),
('Swamp frog'),
('Fungal mage'),
('Ganodermic beast'),
('Ganodermic runt'),
('Gelatinous abomination'),
('Ahrim the Blighted'),
('Akrisae the Doomed'),
('Dharok the Wretched'),
('Ghast'),
('Ghost'),
('Ghost (Abandoned Mine)'),
('Ghost (Ourania Runecrafting Altar)'),
('Ghost (Shattered Worlds)'),
('Ghost (Spirit of Summer)'),
('Ghost (Stronghold of Security)'),
('Ghost healer'),
('Ghostly troll bruiser'),
('Ghostly troll thrower'),
('Ghostly warrior'),
('Guthan the Infested'),
('Karil the Tainted'),
('Linza the Disgraced'),
('Masuta the Descended'),
('Revenant cyclops'),
('Revenant dragon'),
('Revenant goblin'),
('Revenant hellhound'),
('Revenant hobgoblin'),
('Revenant icefiend'),
('Revenant imp'),
('Revenant knight'),
('Revenant ork'),
('Revenant pyrefiend'),
('Revenant vampyre'),
('Revenant werewolf'),
('Risen ghost'),
('Shade'),
('Shadow warrior'),
('Torag the Corrupted'),
('Tormented soul (Uncharted Isles)'),
('Tormented wraith'),
('Tortured soul (Port Phasmatys)'),
('Verac the Defiled'),
('Wight'),
('Wight (Missing, Presumed Death)'),
('Wight ranger'),
('Wight ranger (Sliske''s Endgame)'),
('Ghoul'),
('Ghoul (Paterdomus)'),
('Ravenous ghoul'),
('Ravenous ghoul (Mazchna)'),
('Arch-Glacor'),
('Bolstered Glacyte'),
('Enduring glacyte'),
('Glacor'),
('Glacyte'),
('Glacyte (Arch-Glacor)'),
('Sapping glacyte'),
('Unstable glacyte'),
('Angry goblin'),
('Brokeface'),
('Cave goblin (monster)'),
('Cave goblin guard'),
('Cave goblin miner'),
('Goblin'),
('Goblin (Goblin Village)'),
('Goblin (God Wars Dungeon)'),
('Goblin (Stronghold of Security)'),
('Guard (cave goblin)'),
('Lumpnose'),
('Sergeant Grimspike'),
('Sergeant Steelwill'),
('Sergeant Strongstack'),
('Skoblin'),
('Stinkears'),
('Gorak'),
('Butcher demon'),
('Champion of Infernus'),
('Chaos Demon'),
('Chaos Demon Savage'),
('Denizen of Infernus'),
('Greater demon (elite)'),
('Kor''Vath the Blightbringer'),
('La''Kalor the Unbroken'),
('Shara''Kor the Widowmaker'),
('Grifolapine'),
('Grifolaroo'),
('Giant worm'),
('Grotworm'),
('Mature grotworm'),
('Young grotworm'),
('Harpie Bug Swarm'),
('Harpie Bug Swarm (elite)'),
('Hellhound'),
('Hellhound (Heart of Gielinor)'),
('Hellhound (The Zamorakian Undercity)'),
('Hellhound (summoned)'),
('Hellhound Alpha'),
('Hellhound Hunter'),
('Hellhound Hunter (summoned)'),
('Hill Giant'),
('Hobgoblin'),
('Hobgoblin (elite)'),
('Ice giant'),
('Ice strykewyrm'),
('Ice warrior'),
('Icelord'),
('Icefiend'),
('Icefiend (Ghorrock)'),
('Infernal Mage'),
('Infernal Mage (elite)'),
('Jelly'),
('Jungle horror'),
('Quetzathog'),
('Sea horror'),
('Jungle strykewyrm'),
('Exiled Kalphite Queen'),
('Exiled kalphite guardian'),
('Exiled kalphite marauder'),
('Exiled kalphite paragon'),
('Exiled kalphite soldier'),
('Exiled kalphite worker'),
('Kalphite Guardian'),
('Kalphite King'),
('Kalphite Queen'),
('Kalphite Soldier'),
('Kalphite Worker'),
('Killerwatt'),
('Kurask'),
('Engorged lava strykewyrm'),
('Lava strykewyrm'),
('Lava strykewyrm (Dragonkin Laboratory)'),
('WildyWyrm (2015, historical)'),
('Lesser demon (Wizards'' Tower)'),
('Living rock patriarch'),
('Living rock protector'),
('Living rock striker'),
('Wyvern'),
('Wyvern (elite)'),
('Minotaur'),
('Mogre'),
('Molanisk'),
('Moss giant'),
('Bladed muspah'),
('Force muspah'),
('Throwing muspah'),
('Mutated jadinko baby'),
('Mutated jadinko guard'),
('Mutated jadinko male'),
('Mutated zygomite'),
('Nechryael'),
('Nechryael (Heart of Gielinor)'),
('Nechryael (elite)'),
('Nightmare'),
('Blood nihil'),
('Ice nihil'),
('Shadow nihil'),
('Smoke nihil'),
('Kerapac, the bound'),
('Nodon enforcer'),
('Enclave guard'),
('Ogre'),
('Ogre chieftain'),
('Ogress'),
('Ogress champion'),
('Ogress warrior'),
('Skogre'),
('Zogre'),
('Otherworldly being'),
('Pyrefiend'),
('Pyrefiend (The Zamorakian Undercity)'),
('Pyrefiend (summoned)'),
('Seething Pyrefiend'),
('Smoulders'),
('Smoulders, the Revenger'),
('Angry giant rat'),
('Crypt rat'),
('Dungeon rat'),
('Giant crypt rat'),
('Giant rat'),
('Rat'),
('Warped rat'),
('Slasher Demon'),
('Rock slug'),
('Elite rune dragon'),
('Locust lancer'),
('Locust ranger'),
('Locust rider'),
('Scabaras lancer'),
('Scabaras mage'),
('Scabaras ranger'),
('Scarab akh'),
('Scarab mage'),
('Small scarab'),
('Grave scorpion'),
('King Scorpion'),
('Pit Scorpion'),
('Poison Scorpion'),
('Scorpion'),
('Scorpion (Ape Atoll)'),
('Sea Snake Hatchling'),
('Sea Snake Young'),
('Blissful shadow'),
('Manifest shadow'),
('Shadow (Temple of Light)'),
('Truthful shadow'),
('Skeletal Wyvern'),
('Bossy McBossFace''s First mate'),
('Giant skeleton (Shadow Dungeon)'),
('Giant skeleton (Tarn''s Lair)'),
('Huge skeleton'),
('Skeletal miner'),
('Skeletal shielder'),
('Skeleton'),
('Skeleton (Ape Atoll)'),
('Skeleton (Barrows)'),
('Skeleton (Dark Warriors'' Fortress)'),
('Skeleton (Heart of Gielinor)'),
('Skeleton (Lumbridge Catacombs)'),
('Skeleton (Tarn''s Lair)'),
('Skeleton (Temple Trekking)'),
('Skeleton (Ullek)'),
('Skeleton (Uncharted Isles)'),
('Skeleton Archer'),
('Skeleton Mage'),
('Skeleton archer (Ancient Awakening)'),
('Skeleton brute'),
('Skeleton fremennik'),
('Skeleton heavy'),
('Skeleton hero'),
('Skeleton knight'),
('Skeleton ranger (Ancient Awakening)'),
('Skeleton thug'),
('Skeleton warlord'),
('Skeleton warrior (Ancient Awakening)'),
('Skeleton warrior (Rasial)'),
('Summoned skeleton'),
('Summoned skeleton archer'),
('Training dummy'),
('Undead one'),
('Warped skeleton'),
('Feline akh'),
('Gorilla akh'),
('Imperial mage akh'),
('Imperial ranger akh'),
('Imperial warrior akh'),
('Oreb, the Magister'),
('Salawa akh'),
('The Magister'),
('Soulgazer (elite)'),
('Corpse spider'),
('Crypt spider'),
('Deadly red spider'),
('Giant crypt spider'),
('Giant spider'),
('Ice spider'),
('Jungle spider'),
('Lava spider'),
('Poison spider'),
('Shadow spider'),
('Spider'),
('Spyndra'),
('Veil-ripper Ozharakha'),
('Suqah'),
('Terror dog'),
('Ice troll'),
('Ice troll female'),
('Ice troll grunt'),
('Ice troll male'),
('Ice troll runt'),
('Kraka'),
('Mountain troll'),
('Mountain troll (well)'),
('Pee Hat'),
('River troll'),
('Rock (monster)'),
('Stick'),
('Stove'),
('Thrower Troll'),
('Troll brute'),
('Troll brute (Davendale)'),
('Troll chucker'),
('Troll chucker (Davendale)'),
('Troll general'),
('Troll lout'),
('Troll shaman'),
('Troll shaman (Davendale)'),
('Troll spectator'),
('Undead troll'),
('Turoth'),
('TzHaar-Hur'),
('TzHaar-Ket'),
('TzHaar-Mej'),
('TzHaar-Xil'),
('Animated spade'),
('Armoured zombie'),
('Bloated monstrosity'),
('Corpse archer'),
('Corpse carrier'),
('Corpse mage'),
('Crawling corpse torso'),
('Dragith Nurn'),
('General malpractitioner'),
('Graveside Phantom'),
('Magic axe'),
('Monkey Zombie'),
('Mummy (Jaldraocht Pyramid)'),
('Mummy (Ullek)'),
('Phantom sorcerer'),
('Phantom wizard'),
('Possessed pickaxe'),
('Possessed pickaxe (Lava Flow Mine)'),
('Putrid zombie (Rasial)'),
('Soulless armoured zombie'),
('Soulless unarmoured zombie'),
('Taraket the Necromancer'),
('Undead giant (Battle of Forinthry)'),
('Unstable zombie'),
('Zombie'),
('Zombie (New Varrock)'),
('Zombie cow (New Varrock)'),
('Zombie knight'),
('Zombie pirate'),
('Zombie swab'),
('Zombie warrior'),
('Angry vampyre'),
('Feral vampyre'),
('Vampyre'),
('Vampyre Juvenile'),
('Vampyre Juvinate'),
('Devil''s snare'),
('Lampenflora'),
('Liverworts'),
('Luminous snaggler'),
('Vyrelady'),
('Vyrelord'),
('Vyrewatch'),
('Wall beast'),
('Warped terrorbird'),
('Warped tortoise'),
('Maelstrom, Raging Waterfiend'),
('Torrential Waterfiend'),
('Torrential Waterfiend (summoned)'),
('Waterfiend'),
('Waterfiend (Ghorrock)'),
('Waterfiend (Temple of Aminishi)'),
('Waterfiend (The Zamorakian Undercity)'),
('Waterfiend (elite)'),
('Waterfiend (summoned)'),
('Werewolf'),
('Adolescent White wolf'),
('Big Wolf'),
('Desert wolf'),
('Dire Wolf'),
('Fenris wolf'),
('Fenris wolf (Sköll)'),
('Ice wolf'),
('Jungle Wolf'),
('White wolf'),
('Wolf'),
('Armoured zombie (The Shadow Reef)'),
('Armoured zombie (Uncharted Isles)'),
('Bossy McBossFace'),
('Dried zombie'),
('Empowering zombie'),
('Summoned Zombie'),
('Summoned Zombie (The Shadow Reef)'),
('Summoned armoured zombie'),
('Ulthven Keith'),
('Undead Witch'),
('Zombie (Lair of Tarn Razorlor)'),
('Zombie (Stronghold of Security)'),
('Zombie (Temple Trekking)'),
('Zombie (The Shadow Reef)'),
('Zombie (Uncharted Isles)'),
('Zombie (Wilderness)'),
('Zombie (Zogre Flesh Eaters)'),
('The Ambassador'),
('Araxxi'),
('Chaos Elemental'),
('Commander Zilyana'),
('Croesus'),
('Corporeal Beast'),
('General Graardor'),
('Giant mole'),
('Gregorovic'),
('Har-Aken'),
('Helwyr'),
('Hermod, the Spirit of War'),
('Nex'),
('Nex: Angel of Death'),
('Raksha, the Shadow Colossus'),
('Rasial, the First Necromancer'),
('Seiryu the Azure Serpent'),
('Solak'),
('Telos, the Warden'),
('Nymora, the Vengeful'),
('Avaryss, the Unceasing'),
('TzKal-Zuk'),
('TzTok-Jad'),
('Vindicta'),
('Vorago'),
('Zamorak, Lord of Chaos'),
('Zemouregal'),
('Zombie (Entrana Dungeon)')
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    updated_at = NOW();
