-- Insert into all_equipment or update if the link already exists
INSERT INTO all_equipment (link)
VALUES
('<a href="https://runescape.wiki/w/Ivandis_flail" title="Ivandis flail" target="_blank">Ivandis flail</a>'),
('<a href="https://runescape.wiki/w/Fishing_explosive" title="Fishing explosive" target="_blank">Fishing explosives</a>'),
('<a href="https://runescape.wiki/w/Blisterwood_staff" title="Blisterwood staff" target="_blank">Blisterwood staff</a>'),
('<a href="https://runescape.wiki/w/Gas_mask" title="Gas mask" target="_blank">Gas mask</a>'),
('<a href="https://runescape.wiki/w/Leaf-bladed_sword" title="Leaf-bladed sword" target="_blank">Leaf-bladed sword</a>'),
('<a href="https://runescape.wiki/w/Blisterwood_polearm" title="Blisterwood polearm" target="_blank">Blisterwood polearm</a>'),
('<a href="https://runescape.wiki/w/Spiked_helmet" title="Spiked helmet" target="_blank">Spiked helmet</a>'),
('<a href="https://runescape.wiki/w/Antifire_potion" class="mw-redirect" title="Antifire potion" target="_blank">Antifire potion</a>'),
('<a href="https://runescape.wiki/w/Bug_lantern" class="mw-redirect" title="Bug lantern" target="_blank">Bug lantern</a>'),
('<a href="https://runescape.wiki/w/Earmuffs" title="Earmuffs" target="_blank">Earmuffs</a>'),
('<a href="https://runescape.wiki/w/Slayer_master" class="mw-redirect" title="Slayer master" target="_blank">Slayer master</a>'),
('<a href="https://runescape.wiki/w/Light_source" class="mw-redirect" title="Light source" target="_blank">Light source</a>'),
('<a href="https://runescape.wiki/w/Rock_hammer" title="Rock hammer" target="_blank">Rock hammer</a>'),
('<a href="https://runescape.wiki/w/Mirror_shield" title="Mirror shield" target="_blank">Mirror shield</a>'),
('<a href="https://runescape.wiki/w/Leaf-bladed_spear" title="Leaf-bladed spear" target="_blank">Leaf-bladed spear</a>'),
('<a href="https://runescape.wiki/w/Slayer_Dart" title="Slayer Dart" target="_blank">Slayer Dart</a>'),
('<a href="https://runescape.wiki/w/Broad_arrows" class="mw-redirect" title="Broad arrows" target="_blank">Broad arrows</a>'),
('<a href="https://runescape.wiki/w/Neem_oil" title="Neem oil" target="_blank">Neem oil</a>'),
('<a href="https://runescape.wiki/w/Slayer_gloves" title="Slayer gloves" target="_blank">Slayer gloves</a>'),
('<a href="https://runescape.wiki/w/Insulated_boots" title="Insulated boots" target="_blank">Insulated boots</a>'),
('<a href="https://runescape.wiki/w/Dragonfire_shield" title="Dragonfire shield" target="_blank">Dragonfire shield</a>'),
('<a href="https://runescape.wiki/w/Ice_cooler" title="Ice cooler" target="_blank">Ice cooler</a>'),
('<a href="https://runescape.wiki/w/Super_antifire" title="Super antifire" target="_blank">Super antifire</a>'),
('<a href="https://runescape.wiki/w/Fungicide_spray" title="Fungicide spray" target="_blank">Fungicide spray</a>'),
('<a href="https://runescape.wiki/w/Slayer_helmet" title="Slayer helmet" target="_blank">Slayer helmet</a>'),
('<a href="https://runescape.wiki/w/Wyrmfire_potion" title="Wyrmfire potion" target="_blank">Wyrmfire potion</a>'),
('<a href="https://runescape.wiki/w/Broad-tipped_bolts" title="Broad-tipped bolts" target="_blank">Broad-tipped bolts</a>'),
('<a href="https://runescape.wiki/w/Face_mask" title="Face mask" target="_blank">Face mask</a>'),
('<a href="https://runescape.wiki/w/Super_anti-fire_potion" class="mw-redirect" title="Super anti-fire potion" target="_blank">Super anti-fire potion</a>'),
('<a href="https://runescape.wiki/w/Fire_cape" title="Fire cape" target="_blank">Fire cape</a>'),
('<a href="https://runescape.wiki/w/Anti-dragon_shield" title="Anti-dragon shield" target="_blank">Anti-dragon shield</a>'),
('<a href="https://runescape.wiki/w/Masked_earmuffs" title="Masked earmuffs" target="_blank">Masked earmuffs</a>'),
('<span class="pic-link inventory-image" target="_blank" href="https://runescape.wiki"><span class="mw-default-size" typeof="mw:File"><a href="/w/Neem_oil" title="Neem oil"><img alt="Neem oil.png: RS3 Inventory image of Neem oil" src="/images/Neem_oil.png?f5dec" decoding="async" loading="lazy" width="27" height="29" class="mw-file-element" data-file-width="27" data-file-height="29"></a></span></span>'),
('<a href="https://runescape.wiki/w/Dungeoneering" title="Dungeoneering" target="_blank">Dungeoneering</a>'),
('<a href="https://runescape.wiki/w/Crystal_chime" title="Crystal chime" target="_blank">Crystal chime</a>'),
('<a href="https://runescape.wiki/w/Nose_peg" title="Nose peg" target="_blank">Nose peg</a>'),
('<a href="https://runescape.wiki/w/Witchwood_icon" title="Witchwood icon" target="_blank">Witchwood icon</a>'),
('<a href="https://runescape.wiki/w/Blisterwood_stake" title="Blisterwood stake" target="_blank">Blisterwood stake</a>'),
('<a href="https://runescape.wiki/w/Feather_of_Ma%27at" title="Feather of Ma''at" target="_blank">Feather of Ma''at</a>'),
('<a href="https://runescape.wiki/w/Seal_of_passage" title="Seal of passage" target="_blank">Seal of passage</a>'),
('<a href="https://runescape.wiki/w/Moon_Clan" title="Moon Clan" target="_blank">Moon Clan</a>'),
('<a href="https://runescape.wiki/w/Slayer_bell" title="Slayer bell" target="_blank">Slayer bell</a>'),
('<a href="https://runescape.wiki/w/Super_fishing_explosive" title="Super fishing explosive" target="_blank">Super</a>'),
('<a href="https://runescape.wiki/w/Spiked_gloves" class="mw-redirect" title="Spiked gloves" target="_blank">Spiked gloves</a>'),
('<a href="https://runescape.wiki/w/Elemental_Workshop_equipment" title="Elemental Workshop equipment" target="_blank">Elemental Workshop shield</a>'),
('<a href="https://runescape.wiki/w/Bag_of_salt" title="Bag of salt" target="_blank">Bag of salt</a>'),
('<a href="https://runescape.wiki/w/Spiny_helmet" title="Spiny helmet" target="_blank">Spiny helmet</a>')
ON DUPLICATE KEY UPDATE
    link = VALUES(link),
    updated_at = NOW();
