-- Insert into all_hidden_creatures or update if the name already exists
INSERT INTO all_hidden_creatures (name)
VALUES
('Troll brute (Davendale)'),
('Skeletal hand'),
('Zakl''n Gritch'),
('Skeleton fremennik'),
('Revenant imp'),
('Exiled kalphite guardian'),
('Spiritual ranger'),
('Sea horror'),
('Wyvern (elite)'),
('Gargoyle'),
('Kal''gerion demon'),
('Pekin'),
('Kal''gerion demon (The Shadow Reef)'),
('Waterfiend (elite)'),
('Grave scorpion'),
('Poison Scorpion'),
('Seagull'),
('Guard dog'),
('Ghost (Abandoned Mine)'),
('Hobgoblin (elite)'),
('Skeletal miner'),
('Laboratory slime'),
('Astellarn'),
('Undead cow'),
('Wight ranger (Sliske''s Endgame)'),
('Scorpion (Ape Atoll)'),
('Zombie cow (New Varrock)'),
('Cow calf'),
('Champion of Infernus'),
('Slasher Demon'),
('Giant worm'),
('Cyclossus'),
('Revenant demon'),
('Tormented soul (Uncharted Isles)'),
('Harpie Bug Swarm (elite)'),
('Skogre'),
('Revenant vampyre'),
('King Scorpion'),
('Spiritual mage'),
('Giant slime'),
('Knight of Ardougne (West Ardougne)'),
('Wight ranger'),
('Revenant goblin'),
('Wight (Missing, Presumed Death)'),
('Duckling'),
('Skeleton (Temple Trekking)'),
('Frogeel'),
('Celestial dragon (Dragonkin Laboratory)'),
('Guard (cave goblin)'),
('Butcher demon'),
('Dagannoth fledgeling'),
('Tstanon Karlak'),
('Ghost (Stronghold of Security)'),
('Dark beast (elite)'),
('Tormented wraith'),
('Edimmu (elite)'),
('Greater demon (elite)'),
('Unspeakable horror (elite)'),
('Abyssal demon (elite)'),
('Grizzly bear cub'),
('Zombie hand'),
('Infernal Mage (elite)'),
('Zombie (Zogre Flesh Eaters)'),
('Bear cub'),
('Undead pekin'),
('Penguin (monster)'),
('Tenacious toucan'),
('Revenant ork'),
('Cave goblin (monster)'),
('Brokeface'),
('Pit Scorpion'),
('Soulgazer (elite)'),
('Ghost (Spirit of Summer)'),
('Angry bear'),
('Sea crocodile'),
('Dagannoth spawn'),
('Alanogard the Black'),
('Dagannoth (Waterbirth Island)'),
('Revenant pyrefiend'),
('Nechryael (Heart of Gielinor)'),
('Mourner (Mourner Tunnels)'),
('Wight'),
('Sangri the Red'),
('WildyWyrm (2015, historical)'),
('Dust devil (elite)'),
('Mighty banshee'),
('Revenant dark beast'),
('Tortured soul (Port Phasmatys)'),
('Undead chicken'),
('Dagannoth (Lighthouse)'),
('Cave goblin guard'),
('Nechryael (elite)'),
('Chompy bird'),
('Verak Lith'),
('Seren archer'),
('Fenris wolf'),
('Fenris wolf (Sköll)'),
('Cave horror (elite)'),
('Spiritual warrior'),
('Grizzly bear'),
('Red dragon (Dragonkin Laboratory)'),
('Super Cow'),
('Feral vampyre'),
('Waterfiend (Ghorrock)'),
('Yor''Ger the Deceiver'),
('Giant frog'),
('Mounted terrorbird gnome'),
('Aquanite (elite)'),
('Imp'),
('Revenant hobgoblin'),
('Lumpnose'),
('Sergeant Grimspike'),
('Skeleton (Tarn''s Lair)'),
('Earth warrior (elite)'),
('Elite rune dragon'),
('Verak Little'),
('Icelord'),
('Pernicious parrot'),
('Jubbly bird'),
('Ol'' Sawtooth'),
('Icefiend (Ghorrock)'),
('Bird'),
('Dagannoth guardian'),
('Balfrug Kreeyath'),
('Waterfiend (Temple of Aminishi)'),
('Ankou (elite)'),
('Exiled kalphite marauder'),
('Revenant icefiend'),
('Sergeant Steelwill'),
('Sergeant Strongstack'),
('Quetzathog'),
('Undead one'),
('Big frog'),
('Wild dog'),
('Seren mage'),
('Revenant cyclops'),
('Oreb, the Magister'),
('Ghost (Shattered Worlds)'),
('Hellhound (Heart of Gielinor)'),
('Skoblin'),
('Ghost (Ourania Runecrafting Altar)'),
('Mountain troll (well)'),
('Dagannoth (Waterbirth Island, ranged)'),
('Exiled kalphite paragon'),
('Ravenous ghoul (Mazchna)'),
('Stove'),
('Oomlie bird'),
('Revenant werewolf'),
('Shadow Hound'),
('Cave goblin miner'),
('Rooster'),
('Lava strykewyrm (Dragonkin Laboratory)'),
('Seren warrior'),
('Ghoul (Paterdomus)'),
('Angry goblin'),
('Engorged lava strykewyrm')
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    updated_at = NOW();
