-- Insert into all_locations or update if the link already exists
INSERT INTO all_locations (link)
VALUES
('<a href="https://runescape.wiki/w/Crash_Island" title="Crash Island" target="_blank">Crash Island</a>'),
('<a href="https://runescape.wiki/w/Mazcab" title="Mazcab" target="_blank">Mazcab</a>'),
('<a href="https://runescape.wiki/w/Kharidian_Desert" title="Kharidian Desert" target="_blank">Kharidian Desert</a>'),
('<a href="https://runescape.wiki/w/Waterbirth_Island" title="Waterbirth Island" target="_blank">Waterbirth Island</a>'),
('<a href="https://runescape.wiki/w/Temple_of_Light" title="Temple of Light" target="_blank">Temple of Light</a>'),
('<a href="https://runescape.wiki/w/Black_Arm_Gang" title="Black Arm Gang" target="_blank">Black Arm Gang</a>'),
('<a href="https://runescape.wiki/w/Lumbridge_Swamp" title="Lumbridge Swamp" target="_blank">Lumbridge Swamp</a>'),
('<a href="https://runescape.wiki/w/Varrock_Dig_Site" title="Varrock Dig Site" target="_blank">Varrock Dig Site</a>'),
('<a href="https://runescape.wiki/w/South_Feldip_Hills" title="South Feldip Hills" target="_blank">South Feldip Hills</a>'),
('<a href="https://runescape.wiki/w/Silvarea" title="Silvarea" target="_blank">Silvarea</a>'),
('<a href="https://runescape.wiki/w/Smoke_Dungeon" title="Smoke Dungeon" target="_blank">Smoke Dungeon</a>'),
('<a href="https://runescape.wiki/w/Kuradal%27s_Dungeon" title="Kuradal''s Dungeon" target="_blank">Kuradal''s Dungeon</a>'),
('<a href="https://runescape.wiki/w/Barrows" title="Barrows" target="_blank">Barrows</a>'),
('<a href="https://runescape.wiki/w/Shade_Catacombs" title="Shade Catacombs" target="_blank">Shade Catacombs</a>'),
('<a href="https://runescape.wiki/w/Ape_Atoll_Dungeon" title="Ape Atoll Dungeon" target="_blank">Ape Atoll Dungeon</a>'),
('<a href="https://runescape.wiki/w/Ancient_Cavern" title="Ancient Cavern" target="_blank">Ancient Cavern</a>'),
('<a href="https://runescape.wiki/w/Trollheim" title="Trollheim" target="_blank">Trollheim</a>'),
('<a href="https://runescape.wiki/w/Tarn%27s_Lair" class="mw-redirect" title="Tarn''s Lair" target="_blank">lair of Tarn Razorlor</a>'),
('<a href="https://runescape.wiki/w/Wilderness" title="Wilderness" target="_blank">Wilderness</a>'),
('<a href="https://runescape.wiki/w/Anachronia" title="Anachronia" target="_blank">Anachronia</a>'),
('<a href="https://runescape.wiki/w/Witchaven_Shrine_Dungeon" class="mw-redirect" title="Witchaven Shrine Dungeon" target="_blank">Witchaven Shrine Dungeon</a>'),
('<a href="https://runescape.wiki/w/Pirates%27_Cove" title="Pirates'' Cove" target="_blank">Pirates'' Cove</a>'),
('<a href="https://runescape.wiki/w/Goblin_Cave" title="Goblin Cave" target="_blank">Goblin Cave</a>'),
('<a href="https://runescape.wiki/w/Lunar_Isle" title="Lunar Isle" target="_blank">Lunar Isle</a>'),
('<a href="https://runescape.wiki/w/Nature_altar" title="Nature altar" target="_blank">Nature altar</a>'),
('<a href="https://runescape.wiki/w/Elf_Camp" title="Elf Camp" target="_blank">Elf Camp</a>'),
('<a href="https://runescape.wiki/w/Temple_of_Ikov_(dungeon)" title="Temple of Ikov (dungeon)" target="_blank">Temple of Ikov</a>'),
('<a href="https://runescape.wiki/w/Piscatoris_Fishing_Colony" title="Piscatoris Fishing Colony" target="_blank">Piscatoris Fishing Colony</a>'),
('<a href="https://runescape.wiki/w/Haunted_Mine" title="Haunted Mine" target="_blank">Haunted Mine</a>'),
('<a href="https://runescape.wiki/w/Draynor_Sewers" title="Draynor Sewers" target="_blank">Draynor Sewers</a>'),
('<a href="https://runescape.wiki/w/Ice_troll" title="Ice troll" target="_blank">Ice trolls</a>'),
('<a href="https://runescape.wiki/w/Grotworm_Lair" title="Grotworm Lair" target="_blank">Grotworm Lair</a>'),
('<a href="https://runescape.wiki/w/Frozen_Waste_Plateau" title="Frozen Waste Plateau" target="_blank">Frozen Waste Plateau</a>'),
('<a href="https://runescape.wiki/w/Life_altar" title="Life altar" target="_blank">Life altar</a>'),
('<a href="https://runescape.wiki/w/Freneskae" title="Freneskae" target="_blank">Freneskae</a>'),
('<a href="https://runescape.wiki/w/Killerwatt_plane" title="Killerwatt plane" target="_blank">Killerwatt plane</a>'),
('<a href="https://runescape.wiki/w/Zanaris" title="Zanaris" target="_blank">Zanaris</a>'),
('<a href="https://runescape.wiki/w/Lletya" title="Lletya" target="_blank">Lletya</a>'),
('<a href="https://runescape.wiki/w/Feldip_Hills" title="Feldip Hills" target="_blank">Feldip Hills</a>'),
('<a href="https://runescape.wiki/w/Glacor_Front" title="Glacor Front" target="_blank">Glacor front</a>'),
('<a href="https://runescape.wiki/w/Crandor" title="Crandor" target="_blank">Crandor</a>'),
('<a href="https://runescape.wiki/w/Entrana_Dungeon" title="Entrana Dungeon" target="_blank">Entrana Dungeon</a>'),
('<a href="https://runescape.wiki/w/Ruins_of_Ullek" class="mw-redirect" title="Ruins of Ullek" target="_blank">Ruins of Ullek</a>'),
('<a href="https://runescape.wiki/w/Evil_Chicken%27s_Lair" title="Evil Chicken''s Lair" target="_blank">Evil Chicken''s Lair</a>'),
('<a href="https://runescape.wiki/w/Mammoth_iceberg" title="Mammoth iceberg" target="_blank">Mammoth iceberg</a>'),
('<a href="https://runescape.wiki/w/Dragonkin_Lair" title="Dragonkin Lair" target="_blank">Dragonkin Lair</a>'),
('<a href="https://runescape.wiki/w/Sophanem" title="Sophanem" target="_blank">Sophanem</a>'),
('<a href="https://runescape.wiki/w/TzHaar_city" class="mw-redirect" title="TzHaar city" target="_blank">TzHaar city</a>'),
('<a href="https://runescape.wiki/w/Monastery_of_Ascension" title="Monastery of Ascension" target="_blank">Monastery of Ascension</a>'),
('<a href="https://runescape.wiki/w/Gemstone_cavern" title="Gemstone cavern" target="_blank">Gemstone cavern</a>'),
('<a href="https://runescape.wiki/w/Kal%27gerion_resource_dungeon" title="Kal''gerion resource dungeon" target="_blank">Kal''gerion resource dungeon</a>'),
('<a href="https://runescape.wiki/w/Lighthouse" title="Lighthouse" target="_blank">Lighthouse</a>'),
('<a href="https://runescape.wiki/w/Ogre_Enclave" title="Ogre Enclave" target="_blank">Ogre Enclave</a>'),
('<a href="https://runescape.wiki/w/White_Wolf_Mountain" title="White Wolf Mountain" target="_blank">White Wolf Mountain</a>'),
('<a href="https://runescape.wiki/w/Stalker_Dungeon" class="mw-redirect" title="Stalker Dungeon" target="_blank">Stalker Dungeon</a>'),
('<a href="https://runescape.wiki/w/Lava_Maze_Dungeon" title="Lava Maze Dungeon" target="_blank">Lava Maze Dungeon</a>'),
('<a href="https://runescape.wiki/w/Karamja_Dungeon" class="mw-redirect" title="Karamja Dungeon" target="_blank">Karamja Dungeon</a>'),
('<span class="floornumber" target="_blank" href="https://runescape.wiki"><span class="floornumber-gb">2<sup class="floornumber-ordinal-suffix">nd</sup>&nbsp;floor<sup class="floornumber-help noexcerpt">[<span class="fact-text floor-convention" title="British convention; floor 3 in the US">UK</span>]</sup></span><span class="floornumber-us noexcerpt">3<sup class="floornumber-ordinal-suffix">rd</sup>&nbsp;floor<sup class="floornumber-help noexcerpt">[<span class="fact-text floor-convention" title="US convention; floor 2 in the UK">US</span>]</sup></span></span>'),
('<a href="https://runescape.wiki/w/God_Wars_Dungeon" title="God Wars Dungeon" target="_blank">God Wars Dungeon</a>'),
('<a href="https://runescape.wiki/w/Scorpion_Pit" title="Scorpion Pit" target="_blank">Scorpion Pit</a>'),
('<a href="https://runescape.wiki/w/Lucien%27s_camp" title="Lucien''s camp" target="_blank">Lucien''s camp</a>'),
('<a href="https://runescape.wiki/w/Ancient_Guthix_Temple" class="mw-redirect" title="Ancient Guthix Temple" target="_blank">Ancient Guthix Temple</a>'),
('<a href="https://runescape.wiki/w/Fishing_Guild" title="Fishing Guild" target="_blank">Fishing Guild</a>'),
('<a href="https://runescape.wiki/w/Jade_vine_maze" title="Jade vine maze" target="_blank">Jade vine maze</a>'),
('<a href="https://runescape.wiki/w/Burgh_de_Rott_Woods" title="Burgh de Rott Woods" target="_blank">Burgh de Rott Woods</a>'),
('<a href="https://runescape.wiki/w/Tarn%27s_Lair" class="mw-redirect" title="Tarn''s Lair" target="_blank">Tarn''s Lair</a>'),
('<a href="https://runescape.wiki/w/Fairy_ring" class="mw-redirect" title="Fairy ring" target="_blank">Fairy ring</a>'),
('<a href="https://runescape.wiki/w/Tree_Gnome_Village_(location)" title="Tree Gnome Village (location)" target="_blank">Tree Gnome Village</a>'),
('<a href="https://runescape.wiki/w/Fremennik_Isles" title="Fremennik Isles" target="_blank">Fremennik Isles</a>'),
('<a href="https://runescape.wiki/w/Living_rock_caverns" class="mw-redirect" title="Living rock caverns" target="_blank">Living rock caverns</a>'),
('<a href="https://runescape.wiki/w/Death_Altar" class="mw-redirect" title="Death Altar" target="_blank">Death Altar</a>'),
('<a href="https://runescape.wiki/w/Morytania" title="Morytania" target="_blank">Morytania</a>'),
('<a href="https://runescape.wiki/w/Asgarnian_Ice_Dungeon" title="Asgarnian Ice Dungeon" target="_blank">Asgarnian Ice Dungeon</a>'),
('<a href="https://runescape.wiki/w/Mudskipper_Point" title="Mudskipper Point" target="_blank">Mudskipper Point</a>'),
('<a href="https://runescape.wiki/w/Haunted_Woods" title="Haunted Woods" target="_blank">Haunted Woods</a>'),
('<a href="https://runescape.wiki/w/Al_Kharid" title="Al Kharid" target="_blank">Al Kharid</a>'),
('<a href="https://runescape.wiki/w/Steel_Mine" class="mw-redirect" title="Steel Mine" target="_blank">Steel Mine</a>'),
('<a href="https://runescape.wiki/w/Ripper_Demon_cave" title="Ripper Demon cave" target="_blank">Ripper Demon cave</a>'),
('<a href="https://runescape.wiki/w/Al_Kharid_mining_site" class="mw-redirect" title="Al Kharid mining site" target="_blank">Al Kharid mining site</a>'),
('<a href="https://runescape.wiki/w/Chaos_tunnels" class="mw-redirect" title="Chaos tunnels" target="_blank">Chaos tunnels</a>'),
('<a href="https://runescape.wiki/w/Canifis" title="Canifis" target="_blank">Canifis</a>'),
('<a href="https://runescape.wiki/w/Heroes%27_Guild" title="Heroes'' Guild" target="_blank">Heroes'' Guild</a>'),
('<a href="https://runescape.wiki/w/Burthorpe_Slayer_Cave" title="Burthorpe Slayer Cave" target="_blank">Burthorpe Slayer Cave</a>'),
('<a href="https://runescape.wiki/w/Freneskae#The_Ritual_Site" title="Freneskae" target="_blank">Freneskae (Ritual Site)</a>'),
('<a href="https://runescape.wiki/w/Edgeville_Dungeon" title="Edgeville Dungeon" target="_blank">Edgeville Dungeon</a>'),
('<a href="https://runescape.wiki/w/Amlodd_Clan" title="Amlodd Clan" target="_blank">Amlodd Clan</a>'),
('<a href="https://runescape.wiki/w/Adamant_dragon_dungeon" title="Adamant dragon dungeon" target="_blank">Adamant dragon dungeon</a>'),
('<a href="https://runescape.wiki/w/Wilderness_(level_47)_Lava_Maze_mine" title="Wilderness (level 47) Lava Maze mine" target="_blank">Wilderness (level 47) Lava Maze mine</a>'),
('<a href="https://runescape.wiki/w/Chaos_Druid_Tower" title="Chaos Druid Tower" target="_blank">Chaos Druid Tower</a>'),
('<a href="https://runescape.wiki/w/Lumbridge_Castle" title="Lumbridge Castle" target="_blank">Lumbridge Castle</a>'),
('<a href="https://runescape.wiki/w/Glarial%27s_Tomb" title="Glarial''s Tomb" target="_blank">Glarial''s Tomb</a>'),
('<a href="https://runescape.wiki/w/Forgotten_Cemetery" class="mw-redirect" title="Forgotten Cemetery" target="_blank">Forgotten Cemetery</a>'),
('<a href="https://runescape.wiki/w/Taverley_Dungeon" title="Taverley Dungeon" target="_blank">Taverley Dungeon</a>'),
('<a href="https://runescape.wiki/w/Hobgoblin_Mine" class="mw-redirect" title="Hobgoblin Mine" target="_blank">Hobgoblin Mine</a>'),
('<a href="https://runescape.wiki/w/Gunnarsgrunn" class="mw-redirect" title="Gunnarsgrunn" target="_blank">Gunnarsgrunn</a>'),
('<a href="https://runescape.wiki/w/Hobgoblin_Peninsula" title="Hobgoblin Peninsula" target="_blank">Hobgoblin Peninsula</a>'),
('<a href="https://runescape.wiki/w/Ardougne" title="Ardougne" target="_blank">Ardougne</a>'),
('<a href="https://runescape.wiki/w/Ruins_(east)" title="Ruins (east)" target="_blank">Ruins (east)</a>'),
('<a href="https://runescape.wiki/w/Dealing_with_Scabaras" title="Dealing with Scabaras" target="_blank">Dealing with Scabaras</a>'),
('<a href="https://runescape.wiki/w/Asgarnian_Ice_Caves" class="mw-redirect" title="Asgarnian Ice Caves" target="_blank">Asgarnian Ice Caves</a>'),
('<a href="https://runescape.wiki/w/Digsite_Dungeon" class="mw-redirect" title="Digsite Dungeon" target="_blank">Digsite Dungeon</a>'),
('<a href="https://runescape.wiki/w/Castle_Wars" title="Castle Wars" target="_blank">Castle Wars</a>'),
('<a href="https://runescape.wiki/w/Gu%27Tanoth" title="Gu''Tanoth" target="_blank">Gu''Tanoth</a>'),
('<a href="https://runescape.wiki/w/Gnome_Village_Dungeon" title="Gnome Village Dungeon" target="_blank">Gnome Village Dungeon</a>'),
('<a href="https://runescape.wiki/w/Port_Sarim" title="Port Sarim" target="_blank">Port Sarim</a>'),
('<a href="https://runescape.wiki/w/Wizards%27_Guild" title="Wizards'' Guild" target="_blank">Wizards'' Guild</a>'),
('<a href="https://runescape.wiki/w/Mount_Firewake" title="Mount Firewake" target="_blank">Mount Firewake</a>'),
('<a href="https://runescape.wiki/w/Goblin_Village" title="Goblin Village" target="_blank">Goblin Village</a>'),
('<a href="https://runescape.wiki/w/Darkmeyer" title="Darkmeyer" target="_blank">Darkmeyer</a>'),
('<a href="https://runescape.wiki/w/Brine_Rat_Cavern" title="Brine Rat Cavern" target="_blank">Brine Rat Cavern</a>'),
('<a href="https://runescape.wiki/w/Rellekka" title="Rellekka" target="_blank">Rellekka</a>'),
('<a href="https://runescape.wiki/w/Lumbridge_Swamp_Caves" title="Lumbridge Swamp Caves" target="_blank">Lumbridge Swamp Caves</a>'),
('<a href="https://runescape.wiki/w/Yanille" title="Yanille" target="_blank">Yanille</a>'),
('<a href="https://runescape.wiki/w/Braindeath_Island" title="Braindeath Island" target="_blank">Braindeath Island</a>'),
('<a href="https://runescape.wiki/w/Wizards%27_Tower" title="Wizards'' Tower" target="_blank">Wizards'' Tower</a>'),
('<a href="https://runescape.wiki/w/Wilderness_Crater" title="Wilderness Crater" target="_blank">Wilderness Crater</a>'),
('<a href="https://runescape.wiki/w/Moss_Giant_Island" title="Moss Giant Island" target="_blank">Moss Giant Island</a>'),
('<a href="https://runescape.wiki/w/Troll_cave" title="Troll cave" target="_blank">Troll cave</a>'),
('<a href="https://runescape.wiki/w/Edimmu_resource_dungeon" title="Edimmu resource dungeon" target="_blank">Edimmu resource dungeon</a>'),
('<a href="https://runescape.wiki/w/Draynor_Manor" title="Draynor Manor" target="_blank">Draynor Manor</a>'),
('<a href="https://runescape.wiki/w/Senntisten_Temple" title="Senntisten Temple" target="_blank">Senntisten Temple</a>'),
('<a href="https://runescape.wiki/w/Miscellania_%26_Etceteria_Dungeon" class="mw-redirect" title="Miscellania &amp; Etceteria Dungeon" target="_blank">Miscellania &amp; Etceteria Dungeon</a>'),
('<a href="https://runescape.wiki/w/Stronghold_of_Security" title="Stronghold of Security" target="_blank">Stronghold of Security</a>'),
('<a href="https://runescape.wiki/w/Warriors%27_Guild" title="Warriors'' Guild" target="_blank">Warriors'' Guild</a>'),
('<a href="https://runescape.wiki/w/The_Zamorakian_Undercity" title="The Zamorakian Undercity" target="_blank">The Zamorakian Undercity</a>'),
('<a href="https://runescape.wiki/w/Demonic_ruins" class="mw-redirect" title="Demonic ruins" target="_blank">Demonic ruins</a>'),
('<a href="https://runescape.wiki/w/Ape_Atoll" title="Ape Atoll" target="_blank">Ape Atoll</a>'),
('<a href="https://runescape.wiki/w/Death_Plateau" title="Death Plateau" target="_blank">Death Plateau</a>'),
('<a href="https://runescape.wiki/w/Mountain_troll" title="Mountain troll" target="_blank">Mountain trolls</a>'),
('<a href="https://runescape.wiki/w/Crypt_(Wilderness)" title="Crypt (Wilderness)" target="_blank">Crypt</a>'),
('<a href="https://runescape.wiki/w/Fort_Forinthry" title="Fort Forinthry" target="_blank">Fort Forinthry</a>'),
('<a href="https://runescape.wiki/w/Forinthry_Dungeon" title="Forinthry Dungeon" target="_blank">Forinthry Dungeon</a>'),
('<a href="https://runescape.wiki/w/Slayer_Tower" title="Slayer Tower" target="_blank">Slayer Tower</a>'),
('<a href="https://runescape.wiki/w/Gnome_Stronghold" class="mw-redirect" title="Gnome Stronghold" target="_blank">Gnome Stronghold</a>'),
('<a href="https://runescape.wiki/w/Burthorpe_Troll_Cave" title="Burthorpe Troll Cave" target="_blank">Burthorpe Troll Cave</a>'),
('<a href="https://runescape.wiki/w/McGrubor%27s_Wood" title="McGrubor''s Wood" target="_blank">McGrubor''s Wood</a>'),
('<a href="https://runescape.wiki/w/Mort%27ton" title="Mort''ton" target="_blank">Mort''ton</a>'),
('<a href="https://runescape.wiki/w/Graveyard_of_Shadows" title="Graveyard of Shadows" target="_blank">Graveyard of Shadows</a>'),
('<a href="https://runescape.wiki/w/Lumbridge_catacombs" class="mw-redirect" title="Lumbridge catacombs" target="_blank">Lumbridge catacombs</a>'),
('<a href="https://runescape.wiki/w/River_Elid" title="River Elid" target="_blank">Elid</a>'),
('<a href="https://runescape.wiki/w/Underground_Pass_(dungeon)" title="Underground Pass (dungeon)" target="_blank">Underground Pass (dungeon)</a>'),
('<a href="https://runescape.wiki/w/Stalker_dungeon" title="Stalker dungeon" target="_blank">Stalker dungeon</a>'),
('<a href="https://runescape.wiki/w/Lava_Maze" title="Lava Maze" target="_blank">Lava Maze</a>'),
('<a href="https://runescape.wiki/w/Brimhaven_Dungeon" title="Brimhaven Dungeon" target="_blank">Brimhaven Dungeon</a>'),
('<a href="https://runescape.wiki/w/Prifddinas" title="Prifddinas" target="_blank">Prifddinas</a>'),
('<a href="https://runescape.wiki/w/Ghorrock" title="Ghorrock" target="_blank">Ghorrock</a>'),
('<a href="https://runescape.wiki/w/Clan_Wars" title="Clan Wars" target="_blank">Clan Wars</a>'),
('<a href="https://runescape.wiki/w/Varrock_Sewers" title="Varrock Sewers" target="_blank">Varrock Sewers</a>'),
('<a href="https://runescape.wiki/w/Nodon_Front" title="Nodon Front" target="_blank">Nodon Front</a>'),
('<a href="https://runescape.wiki/w/Deep_Wilderness_Dungeon" title="Deep Wilderness Dungeon" target="_blank">Deep Wilderness Dungeon</a>'),
('<a href="https://runescape.wiki/w/Clock_Tower_Dungeon" title="Clock Tower Dungeon" target="_blank">Clock Tower Dungeon</a>'),
('<a href="https://runescape.wiki/w/Heart_of_Gielinor" title="Heart of Gielinor" target="_blank">Heart of Gielinor</a>'),
('<a href="https://runescape.wiki/w/Resource_dungeon" class="mw-redirect" title="Resource dungeon" target="_blank">Resource dungeon</a>'),
('<a href="https://runescape.wiki/w/Mahjarrat_Ritual_Site_Cavern" class="mw-redirect" title="Mahjarrat Ritual Site Cavern" target="_blank">Mahjarrat Ritual Site Cavern</a>'),
('<a href="https://runescape.wiki/w/Jadinko_Lair" title="Jadinko Lair" target="_blank">Jadinko Lair</a>'),
('<a href="https://runescape.wiki/w/Crypt_(Wilderness)" title="Crypt (Wilderness)" target="_blank">Crypt (Wilderness)</a>'),
('<a href="https://runescape.wiki/w/Coal_truck_mining_site" class="mw-redirect" title="Coal truck mining site" target="_blank">Coal truck mining site</a>'),
('<a href="https://runescape.wiki/w/Mos_Le%27Harmless" title="Mos Le''Harmless" target="_blank">Mos Le''Harmless</a>'),
('<a href="https://runescape.wiki/w/Barendir" title="Barendir" target="_blank">Barendir</a>'),
('<a href="https://runescape.wiki/w/Undead_troll" title="Undead troll" target="_blank">Undead trolls</a>'),
('<a href="https://runescape.wiki/w/Polypore_Dungeon" title="Polypore Dungeon" target="_blank">Polypore Dungeon</a>'),
('<a href="https://runescape.wiki/w/Abyssal_Area" title="Abyssal Area" target="_blank">Abyssal Area</a>'),
('<sup target="_blank" href="https://runescape.wiki">(<a href="/w/Edgeville_Dungeon_hill_giant_resource_dungeon" title="Edgeville Dungeon hill giant resource dungeon">resource dungeon</a>)</sup>'),
('<a href="https://runescape.wiki/w/Kalphite_Lair" class="mw-redirect" title="Kalphite Lair" target="_blank">Kalphite Lair</a>'),
('<a href="https://runescape.wiki/w/Sophanem_Slayer_Dungeon" title="Sophanem Slayer Dungeon" target="_blank">Sophanem Slayer Dungeon</a>'),
('<sup id="cite_ref-4" class="reference" target="_blank" href="https://runescape.wiki"><a href="#cite_note-4">[n 3]</a></sup>'),
('<a href="https://runescape.wiki/w/Red_Dragon_Isle" title="Red Dragon Isle" target="_blank">Red Dragon Isle</a>'),
('<a href="https://runescape.wiki/w/Witchaven_Dungeon" title="Witchaven Dungeon" target="_blank">Witchaven Dungeon</a>'),
('<a href="https://runescape.wiki/w/Soul_Wars" title="Soul Wars" target="_blank">Soul Wars</a>'),
('<a href="https://runescape.wiki/w/Legends%27_Guild" title="Legends'' Guild" target="_blank">Legends'' Guild</a>'),
('<a href="https://runescape.wiki/w/Mos_Le%27Harmless_Caves" title="Mos Le''Harmless Caves" target="_blank">Mos Le''Harmless Caves</a>'),
('<a href="https://runescape.wiki/w/Brimhaven" title="Brimhaven" target="_blank">Brimhaven</a>'),
('<a href="https://runescape.wiki/w/Underground_Pass_(dungeon)" title="Underground Pass (dungeon)" target="_blank">Underground Pass</a>'),
('<a href="https://runescape.wiki/w/Stronghold_of_Player_Safety" title="Stronghold of Player Safety" target="_blank">Stronghold of Player Safety</a>'),
('<a href="https://runescape.wiki/w/Ardougne_Zoo" title="Ardougne Zoo" target="_blank">Ardougne Zoo</a>'),
('<a href="https://runescape.wiki/w/Karamja" title="Karamja" target="_blank">Karamja</a>'),
('<a href="https://runescape.wiki/w/Poison_Waste_Slayer_Dungeon" title="Poison Waste Slayer Dungeon" target="_blank">Poison Waste Slayer Dungeon</a>'),
('<a href="https://runescape.wiki/w/Sorceress" title="Sorceress" target="_blank">Sorceress</a>'),
('<a href="https://runescape.wiki/w/Pollnivneach_Slayer_Dungeon" title="Pollnivneach Slayer Dungeon" target="_blank">Pollnivneach Slayer Dungeon</a>'),
('<span class="fairycode" style="word-break:keep-all" target="_blank" href="https://runescape.wiki"><b>D</b><b>I</b><b>R</b></span>'),
('<a href="https://runescape.wiki/w/Senntisten_Asylum" title="Senntisten Asylum" target="_blank">Senntisten Asylum</a>'),
('<a href="https://runescape.wiki/w/Ice_strykewyrm_cave" title="Ice strykewyrm cave" target="_blank">Ice strykewyrm cave</a>'),
('<a href="https://runescape.wiki/w/Camel_Warriors_island" title="Camel Warriors island" target="_blank">Camel Warriors island</a>'),
('<a href="https://runescape.wiki/w/Agility_pyramid" class="mw-redirect" title="Agility pyramid" target="_blank">Agility pyramid</a>'),
('<a href="https://runescape.wiki/w/Freneskae#The_Pit" title="Freneskae" target="_blank">Freneskae (the Pit)</a>'),
('<a href="https://runescape.wiki/w/Crandor_Isle" class="mw-redirect" title="Crandor Isle" target="_blank">Crandor Isle</a>'),
('<a href="https://runescape.wiki/w/Glacor_Cave" title="Glacor Cave" target="_blank">Glacor Cave</a>'),
('<a href="https://runescape.wiki/w/Combat_Training_Camp" title="Combat Training Camp" target="_blank">Combat Training Camp</a>'),
('<a href="https://runescape.wiki/w/Temple_Trekking" title="Temple Trekking" target="_blank">Temple Trekking</a>'),
('<a href="https://runescape.wiki/w/Karamja_Volcano" title="Karamja Volcano" target="_blank">Karamja Volcano</a>'),
('<a href="https://runescape.wiki/w/Abandoned_Mine" title="Abandoned Mine" target="_blank">Abandoned Mine</a>'),
('<a href="https://runescape.wiki/w/Melzar%27s_Maze" title="Melzar''s Maze" target="_blank">Melzar''s Maze</a>'),
('<a href="https://runescape.wiki/w/Dragontooth_Island_resource_dungeon" title="Dragontooth Island resource dungeon" target="_blank">Dragontooth Island resource dungeon</a>'),
('<a href="https://runescape.wiki/w/Meiyerditch_Dungeon" class="mw-redirect" title="Meiyerditch Dungeon" target="_blank">Meiyerditch Dungeon</a>'),
('<a href="https://runescape.wiki/w/Keldagrim" title="Keldagrim" target="_blank">Keldagrim</a>'),
('<a href="https://runescape.wiki/w/Tarddiad" title="Tarddiad" target="_blank">Tarddiad</a>'),
('<a href="https://runescape.wiki/w/The_Lost_Grove" title="The Lost Grove" target="_blank">The Lost Grove</a>'),
('<a href="https://runescape.wiki/w/Ice_mountain" class="mw-redirect" title="Ice mountain" target="_blank">Ice mountain</a>'),
('<a href="https://runescape.wiki/w/Observatory" title="Observatory" target="_blank">Observatory</a>'),
('<a href="https://runescape.wiki/w/Meiyerditch" title="Meiyerditch" target="_blank">Meiyerditch</a>'),
('<a href="https://runescape.wiki/w/Fremennik_Slayer_Dungeon" title="Fremennik Slayer Dungeon" target="_blank">Fremennik Slayer Dungeon</a>'),
('<a href="https://runescape.wiki/w/Crypt_(Wilderness)" title="Crypt (Wilderness)" target="_blank">crypt</a>'),
('<a href="https://runescape.wiki/w/Guthix%27s_Cave" class="mw-redirect" title="Guthix''s Cave" target="_blank">Guthix''s Cave</a>'),
('<a href="https://runescape.wiki/w/Chaos_Tunnels" title="Chaos Tunnels" target="_blank">Chaos Tunnels</a>'),
('<a href="https://runescape.wiki/w/Demonic_Ruins" title="Demonic Ruins" target="_blank">Demonic Ruins</a>'),
('<a href="https://runescape.wiki/w/Exiled_Kalphite_Hive" title="Exiled Kalphite Hive" target="_blank">Exiled Kalphite Hive</a>'),
('<a href="https://runescape.wiki/w/Waterfall_Dungeon" title="Waterfall Dungeon" target="_blank">Waterfall Dungeon</a>'),
('<a href="https://runescape.wiki/w/Lumbridge_Catacombs" title="Lumbridge Catacombs" target="_blank">Lumbridge Catacombs</a>'),
('<a href="https://runescape.wiki/w/Dorgesh-Kaan_South_Dungeon" title="Dorgesh-Kaan South Dungeon" target="_blank">Dorgesh-Kaan South Dungeon</a>'),
('<a href="https://runescape.wiki/w/Deserted_Keep" title="Deserted Keep" target="_blank">Deserted Keep</a>'),
('<a href="https://runescape.wiki/w/Dwarven_mines" title="Dwarven mines" target="_blank">Dwarven mines</a>')
ON DUPLICATE KEY UPDATE
    link = VALUES(link),
    updated_at = NOW();
